# CMAKE generated file: DO NOT EDIT!
# Generated by "MinGW Makefiles" Generator, CMake Version 4.2

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

SHELL = cmd.exe

# The CMake executable.
CMAKE_COMMAND = C:\CMake\bin\cmake.exe

# The command to remove a file.
RM = C:\CMake\bin\cmake.exe -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = C:\Monefy

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = C:\Monefy

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target package
package: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Run CPack packaging tool..."
	C:\CMake\bin\cpack.exe --config ./CPackConfig.cmake
.PHONY : package

# Special rule for the target package
package/fast: package
.PHONY : package/fast

# Special rule for the target package_source
package_source:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Run CPack packaging tool for source..."
	C:\CMake\bin\cpack.exe --config ./CPackSourceConfig.cmake
.PHONY : package_source

# Special rule for the target package_source
package_source/fast: package_source
.PHONY : package_source/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	C:\CMake\bin\cmake-gui.exe -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	C:\CMake\bin\cmake.exe --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Install the project..."
	C:\CMake\bin\cmake.exe -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Install the project..."
	C:\CMake\bin\cmake.exe -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing only the local directory..."
	C:\CMake\bin\cmake.exe -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing only the local directory..."
	C:\CMake\bin\cmake.exe -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing the project stripped..."
	C:\CMake\bin\cmake.exe -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing the project stripped..."
	C:\CMake\bin\cmake.exe -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start C:\Monefy\CMakeFiles C:\Monefy\\CMakeFiles\progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start C:\Monefy\CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles\Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named monefy_server

# Build rule for target.
monefy_server: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 monefy_server
.PHONY : monefy_server

# fast build rule for target.
monefy_server/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\monefy_server.dir\build.make CMakeFiles/monefy_server.dir/build
.PHONY : monefy_server/fast

#=============================================================================
# Target rules for targets named uninstall

# Build rule for target.
uninstall: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 uninstall
.PHONY : uninstall

# fast build rule for target.
uninstall/fast:
	$(MAKE) $(MAKESILENT) -f _deps\crow-build\CMakeFiles\uninstall.dir\build.make _deps/crow-build/CMakeFiles/uninstall.dir/build
.PHONY : uninstall/fast

backend/main.obj: backend/main.cpp.obj
.PHONY : backend/main.obj

# target to build an object file
backend/main.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\monefy_server.dir\build.make CMakeFiles/monefy_server.dir/backend/main.cpp.obj
.PHONY : backend/main.cpp.obj

backend/main.i: backend/main.cpp.i
.PHONY : backend/main.i

# target to preprocess a source file
backend/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\monefy_server.dir\build.make CMakeFiles/monefy_server.dir/backend/main.cpp.i
.PHONY : backend/main.cpp.i

backend/main.s: backend/main.cpp.s
.PHONY : backend/main.s

# target to generate assembly for a file
backend/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\monefy_server.dir\build.make CMakeFiles/monefy_server.dir/backend/main.cpp.s
.PHONY : backend/main.cpp.s

backend/services/TransactionService.obj: backend/services/TransactionService.cpp.obj
.PHONY : backend/services/TransactionService.obj

# target to build an object file
backend/services/TransactionService.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\monefy_server.dir\build.make CMakeFiles/monefy_server.dir/backend/services/TransactionService.cpp.obj
.PHONY : backend/services/TransactionService.cpp.obj

backend/services/TransactionService.i: backend/services/TransactionService.cpp.i
.PHONY : backend/services/TransactionService.i

# target to preprocess a source file
backend/services/TransactionService.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\monefy_server.dir\build.make CMakeFiles/monefy_server.dir/backend/services/TransactionService.cpp.i
.PHONY : backend/services/TransactionService.cpp.i

backend/services/TransactionService.s: backend/services/TransactionService.cpp.s
.PHONY : backend/services/TransactionService.s

# target to generate assembly for a file
backend/services/TransactionService.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\monefy_server.dir\build.make CMakeFiles/monefy_server.dir/backend/services/TransactionService.cpp.s
.PHONY : backend/services/TransactionService.cpp.s

backend/storage/AccountStorage.obj: backend/storage/AccountStorage.cpp.obj
.PHONY : backend/storage/AccountStorage.obj

# target to build an object file
backend/storage/AccountStorage.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\monefy_server.dir\build.make CMakeFiles/monefy_server.dir/backend/storage/AccountStorage.cpp.obj
.PHONY : backend/storage/AccountStorage.cpp.obj

backend/storage/AccountStorage.i: backend/storage/AccountStorage.cpp.i
.PHONY : backend/storage/AccountStorage.i

# target to preprocess a source file
backend/storage/AccountStorage.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\monefy_server.dir\build.make CMakeFiles/monefy_server.dir/backend/storage/AccountStorage.cpp.i
.PHONY : backend/storage/AccountStorage.cpp.i

backend/storage/AccountStorage.s: backend/storage/AccountStorage.cpp.s
.PHONY : backend/storage/AccountStorage.s

# target to generate assembly for a file
backend/storage/AccountStorage.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\monefy_server.dir\build.make CMakeFiles/monefy_server.dir/backend/storage/AccountStorage.cpp.s
.PHONY : backend/storage/AccountStorage.cpp.s

backend/storage/CategoryStorage.obj: backend/storage/CategoryStorage.cpp.obj
.PHONY : backend/storage/CategoryStorage.obj

# target to build an object file
backend/storage/CategoryStorage.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\monefy_server.dir\build.make CMakeFiles/monefy_server.dir/backend/storage/CategoryStorage.cpp.obj
.PHONY : backend/storage/CategoryStorage.cpp.obj

backend/storage/CategoryStorage.i: backend/storage/CategoryStorage.cpp.i
.PHONY : backend/storage/CategoryStorage.i

# target to preprocess a source file
backend/storage/CategoryStorage.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\monefy_server.dir\build.make CMakeFiles/monefy_server.dir/backend/storage/CategoryStorage.cpp.i
.PHONY : backend/storage/CategoryStorage.cpp.i

backend/storage/CategoryStorage.s: backend/storage/CategoryStorage.cpp.s
.PHONY : backend/storage/CategoryStorage.s

# target to generate assembly for a file
backend/storage/CategoryStorage.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\monefy_server.dir\build.make CMakeFiles/monefy_server.dir/backend/storage/CategoryStorage.cpp.s
.PHONY : backend/storage/CategoryStorage.cpp.s

backend/storage/TransactionStorage.obj: backend/storage/TransactionStorage.cpp.obj
.PHONY : backend/storage/TransactionStorage.obj

# target to build an object file
backend/storage/TransactionStorage.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\monefy_server.dir\build.make CMakeFiles/monefy_server.dir/backend/storage/TransactionStorage.cpp.obj
.PHONY : backend/storage/TransactionStorage.cpp.obj

backend/storage/TransactionStorage.i: backend/storage/TransactionStorage.cpp.i
.PHONY : backend/storage/TransactionStorage.i

# target to preprocess a source file
backend/storage/TransactionStorage.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\monefy_server.dir\build.make CMakeFiles/monefy_server.dir/backend/storage/TransactionStorage.cpp.i
.PHONY : backend/storage/TransactionStorage.cpp.i

backend/storage/TransactionStorage.s: backend/storage/TransactionStorage.cpp.s
.PHONY : backend/storage/TransactionStorage.s

# target to generate assembly for a file
backend/storage/TransactionStorage.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\monefy_server.dir\build.make CMakeFiles/monefy_server.dir/backend/storage/TransactionStorage.cpp.s
.PHONY : backend/storage/TransactionStorage.cpp.s

backend/storage/UserStorage.obj: backend/storage/UserStorage.cpp.obj
.PHONY : backend/storage/UserStorage.obj

# target to build an object file
backend/storage/UserStorage.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\monefy_server.dir\build.make CMakeFiles/monefy_server.dir/backend/storage/UserStorage.cpp.obj
.PHONY : backend/storage/UserStorage.cpp.obj

backend/storage/UserStorage.i: backend/storage/UserStorage.cpp.i
.PHONY : backend/storage/UserStorage.i

# target to preprocess a source file
backend/storage/UserStorage.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\monefy_server.dir\build.make CMakeFiles/monefy_server.dir/backend/storage/UserStorage.cpp.i
.PHONY : backend/storage/UserStorage.cpp.i

backend/storage/UserStorage.s: backend/storage/UserStorage.cpp.s
.PHONY : backend/storage/UserStorage.s

# target to generate assembly for a file
backend/storage/UserStorage.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\monefy_server.dir\build.make CMakeFiles/monefy_server.dir/backend/storage/UserStorage.cpp.s
.PHONY : backend/storage/UserStorage.cpp.s

# Help Target
help:
	@echo The following are some of the valid targets for this Makefile:
	@echo ... all (the default if no target is provided)
	@echo ... clean
	@echo ... depend
	@echo ... edit_cache
	@echo ... install
	@echo ... install/local
	@echo ... install/strip
	@echo ... list_install_components
	@echo ... package
	@echo ... package_source
	@echo ... rebuild_cache
	@echo ... uninstall
	@echo ... monefy_server
	@echo ... backend/main.obj
	@echo ... backend/main.i
	@echo ... backend/main.s
	@echo ... backend/services/TransactionService.obj
	@echo ... backend/services/TransactionService.i
	@echo ... backend/services/TransactionService.s
	@echo ... backend/storage/AccountStorage.obj
	@echo ... backend/storage/AccountStorage.i
	@echo ... backend/storage/AccountStorage.s
	@echo ... backend/storage/CategoryStorage.obj
	@echo ... backend/storage/CategoryStorage.i
	@echo ... backend/storage/CategoryStorage.s
	@echo ... backend/storage/TransactionStorage.obj
	@echo ... backend/storage/TransactionStorage.i
	@echo ... backend/storage/TransactionStorage.s
	@echo ... backend/storage/UserStorage.obj
	@echo ... backend/storage/UserStorage.i
	@echo ... backend/storage/UserStorage.s
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles\Makefile.cmake 0
.PHONY : cmake_check_build_system

